### ISSUE TITLE
prospective projections/predictions

### ISSUE THREAD

**Issue by topepo** [gdkrmr/dimRed#1]
Can you add a functions or classes that will allow the model to be estimated from a data set and then applied to any other data set? This wouldn't work for every method (e.g. MDS) but would be extremely useful. 

For example, with PCA: 
```r
set.seed(12)
for_mod <- sample(1:nrow(USArrests), 40)

pca_mod <- prcomp(~ Murder + Assault + Rape, data = USArrests[for_mod, ], scale = TRUE)

## now apply the projection onto any data set:
pca_mod_data   <- predict(pca_mod, USArrests[ for_mod, ])
pca_other_data <- predict(pca_mod, USArrests[-for_mod, ])
```

Thanks

**Comment by gdkrmr** [comment]
I just saw, that the feature is completely undocumented and hides in some examples.
I will make a predict and inverse function for the next release, but for now you can use (for supported methods only):
```R
emb <- embed(loadDataSet("Iris")[1:50], "PCA")
pred <- emb@apply(loadDataSet("Iris")[51:150])
emb@inverse(pred)
```

**Comment by topepo** [comment]
Excellent. I'm writing (another) feature pre-processor that includes signal extraction, so I'll keep an eye on your updates and will post questions here if they come up. 

Thanks

**Comment by gdkrmr** [comment]
just pushed the predict and inverse functions, they are documented with the dimRedResults class
