### ISSUE TITLE
Wish: quality methods for coRanking matrices

### ISSUE THREAD

**Issue by ugroempi** [gdkrmr/dimRed#14]
It would be great if the quality methods would directly work on coRanking matrices.

Best, Ulrike

**Comment by gdkrmr** [comment]
for that use the `coRanking` package: https://cran.r-project.org/web/packages/coRanking/index.html

**Comment by ugroempi** [comment]
which has a single quality metric at the moment ...
I thought that you had abandoned quality metrics in coRanking in favor of dimRed? (There is a file with many unexported and undocumented functions, but ...)

Best, Ulrike

**Comment by gdkrmr** [comment]
no, dimRed mostly wraps other packages, and coRanking is one of them. I never had the time to document all the unexported functions, pull requests are welcome ;-)
