### ISSUE TITLE
Wish: improved documentation

### ISSUE THREAD

**Issue by ugroempi** [gdkrmr/dimRed#15]
The written documentation is very scarce (probably a consequence of using Roxygen ...). More detail would be helpful.

Technically, due to the documentation file names, the "see also" links are absolutely horrible; they would be much more helpful in their obvious short version. Can that be changed?

Best, Ulrike

**Comment by gdkrmr** [comment]
regarding 1) I have a manuscript submitted to the RJournal and I am waiting for the reply of the editors for almost half a year now, there I describe each method shortly.

regarding 2) don't know I will look into it

**Comment by gdkrmr** [comment]
1) is also the reason why he develop branch is so far ahead of the CRAN version, I will not update the CRAN version until I have this manuscript published. The idea was to turn it into a vignette and update with new methods. That is why the nnmf branch of recipes will probably keep failing for a while @topepo.

**Comment by topepo** [comment]
I'm keeping that branch of recipes on ice until a new `dimRed` is released. I'll look into whether 
 `Remotes` can be used to point to a specific branch.

**Comment by gdkrmr** [comment]
@ugroempi Regarding your second point: I had a quick look at it and you are right, the `-class` is ugly but I have no idea how to fix this. Roxygen creates aliases `Isomap` and `Isomap-class` in the help index but puts `Isomap-class` in the `see also` section.
If you figure out how to do this, let me know and I will fix this.

**Comment by gdkrmr** [comment]
@ugroempi the paper finally got accepted: https://journal.r-project.org/archive/2018/RJ-2018-039/index.html
The plan is to treat is as a living document and to include it as a vignette, if this is possible.
