### ISSUE TITLE
LandMark ISOMAP

### ISSUE THREAD

**Issue by yancychy** [gdkrmr/dimRed#21]
Hi, the ISOMAP function run fast. But Is there any method to automatically select landmark points in your ISOMAP?  Many thanks.

**Comment by yancychy** [comment]
I find Rdimtools can implement this. But it runs slowly.

**Comment by gdkrmr** [comment]
no, there is not. If you give me a reference I may implement this in the future.

**Comment by yancychy** [comment]
Thanks. But when I run a sample with 30333 size. It costs 45279.441 seconds, almost 12.5 hours. 
But t-SNE and PCA cost 14187.45 and 14201.332 respectively (4 hours). 
So I tired the Landmark ISOMAP, but the results are not good for visualization. 

    dat = dimRedData(Z) # 
    samp <- sample(nrow(dat), size = 200)
    emb2 <- embed(dat[samp,], "Isomap",knn= 10)
    emb3 <- emb2@apply(dat[-samp])
    #plot(emb2, type = "2vars")
    #plot(emb3, type = "2vars")
    X = rbind(emb2@data@data, emb3@data)

**Comment by yancychy** [comment]
I know two papers which proposed a faster Landmark ISOMAP.
1.Lei Y K, You Z H, Dong T, et al. Increasing reliability of protein interactome by fast manifold embedding[J]. Pattern Recognition Letters, 2013, 34(4):372-379.
2. Shi H, Yin B, Kang Y, et al. Robust L-Isomap with a Novel Landmark Selection Method[J]. Mathematical Problems in Engineering,2017,  2017(5552, article 7):1-12.

**Comment by gdkrmr** [comment]
In order for Isomap to work nicely, the underlying manifold needs to be "unfoldable" to 2d or 3d euclidean space, if this is not given, Isomap will not produce usable output.

The running time for t-SNE and pca seems a little bit high, t-SNE should be able to embed 70000 points in under 30 minutes.

**Comment by yancychy** [comment]
Ok, thanks. I think it is my computer too old.
