### ISSUE TITLE
Vignette Contribution

### ISSUE THREAD

**Issue by talegari** [gdkrmr/dimRed#29]
Dear Guido Kraemer,

Thanks for the package! I am thinking of contributing a vignette that you help users to quickly understand how to use the package (more on the usage side than illustrating different methods). Is it a good idea?

Regards,
Srikanth KS

**Comment by gdkrmr** [comment]
Better documentation is always welcome! To avoid duplicated effort be aware that I just added a vignette (basically the contents of [this](https://journal.r-project.org/archive/2018/RJ-2018-039/index.html) paper) that explains the different methods and usage.
