### ISSUE TITLE
spurious error when testing

### ISSUE THREAD

**Issue by gdkrmr** [gdkrmr/dimRed#30]
Sometimes I get the follwing error when testing:

```
✖ | 14 1     | the dimRedData class
────────────────────────────────────────────────────────────────────────────────
test_dimRedData.R:31: failure: misc functions
nrow(Iris) not equal to 150.
target is NULL, current is numeric
────────────────────────────────────────────────────────────────────────────────
```

happens when using `devtools::test()` and `R CMD check --run-donttest --run-dontrun --timings`

**Comment by topepo** [comment]
Anything that I can do to help?

**Comment by gdkrmr** [comment]
The error disappeared, even for R 3.4.4. It never appeared in version 3.5.1 or R-devel. I will close this as an R bug.

**Comment by gdkrmr** [comment]
This was due to importing NMF, should be resolved.
