### ISSUE TITLE
HHLE fails for ndim=1

### ISSUE THREAD

**Issue by khughitt** [gdkrmr/dimRed#38]
The `HHLE` method appears not to work when `ndim` is set to `1`.

**To reproduce**:

``` r
library(dimRed)
```

    ## Loading required package: DRR

    ## Loading required package: kernlab

    ## Loading required package: CVST

    ## Loading required package: Matrix

    ## 
    ## Attaching package: 'dimRed'

    ## The following object is masked from 'package:stats':
    ## 
    ##     embed

    ## The following object is masked from 'package:base':
    ## 
    ##     as.data.frame

``` r
set.seed(1)

embed(matrix(rnorm(1E5), 100), 'HLLE', ndim = 1, knn = 10)
```

    ## 2019-01-26 23:42:42: Finding nearest neighbors

    ## 2019-01-26 23:42:42: Calculating Hessian

    ## 1/100

    ## Error in combn(seq_len(pars$ndim), 2): n < m

**System Information**:

``` r
sessionInfo()
```

    ## R version 3.5.2 (2018-12-20)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Arch Linux
    ## 
    ## Matrix products: default
    ## BLAS: /usr/lib/libblas.so.3.8.0
    ## LAPACK: /usr/lib/liblapack.so.3.8.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] dimRed_0.2.2   DRR_0.0.3      CVST_0.2-2     Matrix_1.2-15 
    ## [5] kernlab_0.9-27 nvimcom_0.9-75 colorout_1.2-0
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] RANN_2.6.1         Rcpp_1.0.0         lattice_0.20-38   
    ##  [4] digest_0.6.18      RSpectra_0.13-1    grid_3.5.2        
    ##  [7] magrittr_1.5       evaluate_0.12      stringi_1.2.4     
    ## [10] rmarkdown_1.11     tools_3.5.2        stringr_1.3.1     
    ## [13] xfun_0.4           yaml_2.2.0         compiler_3.5.2    
    ## [16] BiocManager_1.30.4 htmltools_0.3.6    knitr_1.21

**Comment by gdkrmr** [comment]
I took a quick look at the HLLE algorithm and the original paper only mentions d >= 2, at the first glace I see no obvious way to do it of d == 1 and therefore made it an error. Do you have any real use case for this?

**Comment by khughitt** [comment]
Hi @gdkrmr Thanks for the quick follow-up. I am interest in comparing different methods for 1d projection, but am not married to this method. If it was originally intended to created embeddings in d >=2, then a note and/or warning would do the trick. Thanks!

**Comment by gdkrmr** [comment]
Thanks for the reports :-) ! I can try something that I think may work if you are interested in evaluating it.

**Comment by gdkrmr** [comment]
I you want to try HLLE for ndim = 1 and evaluate it, please reopen.
