### ISSUE TITLE
Inverse function for tsne and umap

### ISSUE THREAD

**Issue by NikitaGupta0908** [gdkrmr/dimRed#48]
Hi,
I am trying to find the reconstruction error for umap and tsne. I get this error.

```
ir <- loadDataSet("3D S Curve")
ir.umap <- embed(ir, "UMAP", ndim = ndims(ir))
ir.tsne <- embed(ir, "tSNE", ndim = ndims(ir))
rmse <- data.frame(
rmse_umap = reconstruction_error(ir.umap),
rmse_tsne = reconstruction_error(ir.tsne)
)
matplot(rmse, type = "l")
plot(ir)
plot(ir.umap)
plot(ir.tsne)

```
This gives me an error:
Error in .local(object, ...): object does not have an inverse function
Traceback:

data.frame(rmse_umap = reconstruction_error(ir.umap), rmse_tsne = reconstruction_error(ir.tsne))
reconstruction_error(ir.umap)
reconstruction_error(ir.umap)
.local(object, ...)
getData(inverse(object, getData(getDimRedData(object))[, seq_len(n[i]),
. drop = FALSE]))
inverse(object, getData(getDimRedData(object))[, seq_len(n[i]),
. drop = FALSE])
inverse(object, getData(getDimRedData(object))[, seq_len(n[i]),
. drop = FALSE])
.local(object, ...)
stop("object does not have an inverse function")

Please let me know where am I going wrong/ how to fix this issue. Thanks!

**Comment by gdkrmr** [comment]
there is no inverse function implemented for UMAP, therefore no reconstruction and no reconstruction error.
